name: Build

on:
  push:
    branches:
    - master
    # For testing.
    - actions
    tags:
      - "v*.*"
    paths-ignore:
    - '*.{txt,md}'
    - 'Tools/**'
    - '.{editorconfig,gitattributes,gitignore}'
    - 'appveyor.yml'
  pull_request:
    branches:
    - master
    paths-ignore:
    - '*.{txt,md}'
    - 'Tools/**'
    - '.{editorconfig,gitattributes,gitignore}'
    - 'appveyor.yml'

env:
  BUILD_CONFIGURATION: Release

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Install Clang
      uses: ilammy/setup-clang@v1.12.0  # 替换为具体可用的版本号
      with:
        version: '14'  # 可根据需要调整 Clang 版本

    - name: Build Windows with Clang
      working-directory: ${{ env.GITHUB_WORKSPACE }}
      shell: cmd
      run: |
        set "CC=clang.exe"
        set "CXX=clang++.exe"
        msbuild /m /p:TrackFileAccess=false /p:Configuration=${{ env.BUILD_CONFIGURATION }} /p:Platform=x64 /p:PreferredToolArchitecture=x64 /p:PlatformToolset=ClangCL Windows/PPSSPP.sln

    - name: Package build
      working-directory: ${{ env.GITHUB_WORKSPACE }}
      run: |
        mkdir ppsspp
        cp PPSSPP*.exe ppsspp/
        cp *.pdb ppsspp/
        cp Windows/*.bat ppsspp/
        cp -r assets ppsspp/assets

    - name: Package headless
      run: cp Windows/x64/Release/*.exe ppsspp/

    - name: Upload build
      uses: actions/upload-artifact@v4
      with:
        name: Windows x64 build
        path: ppsspp/
